export enum NewsType {
  ALL = 'ALL',
  CRYPTOGRAPHY = 'CRYPTOGRAPHY',
  INFORMATICS_AND_COMPUTER_SECURITY = 'INFORMATICS_AND_COMPUTER_SECURITY',
  PHYSICS = 'PHYSICS',
  FOREIGN_LANGUAGE = 'FOREIGN_LANGUAGE',
  MATHEMATICS = 'MATHEMATICS',
  SOCIAL_SCIENCE = 'SOCIAL_SCIENCE',
  RUSSIAN_LANGUAGE = 'RUSSIAN_LANGUAGE',
}

export enum NewsView {
  BIG = 'BIG',
  SMALL = 'SMALL',
}